name: 'setup-bds'
description: 'An action to download and setup minecraft bds for testing environments'
author: 'ScriptAPIOSS'
inputs:
  TARGET_SOURCE_PATHS:
    required: true
    description: 'Paths to package'
  TARGET_DEST_PATH:
    required: true
    description: 'Paths to package'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'yellow'
